ignores:
  - depcheck
  - declapract
  - declapract-typescript-ehmpathy
  - '@commitlint/config-conventional'
  - '@trivago/prettier-plugin-sort-imports'
  - '@tsconfig/node-lts-strictest'
  - core-js
  - ts-jest
  - husky
  - '@oclif/plugin-help'
  - oclif
  - ts-node

# directories to not check for dependencies in
ignorePatterns:
  - src/**/__test_assets__/** # these test assets contain imports we ignore
